import Head from 'next/head'

const Header = (): JSX.Element => {
    return (
        <Head>
            <title>Profile</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default Header